#  Copyright (c) 2026. Bigness League.
#
#  Licensed under the GNU General Public License v3.0
#
#  https://www.gnu.org/licenses/gpl-3.0.html
#
#  Permissions of this strong copyleft license are conditioned on making available complete source code of licensed
#  works and modifications, which include larger works using a licensed work, under the same license. Copyright and
#  license notices must be preserved. Contributors provide an express grant of patent rights.

from __future__ import annotations

import argparse
import json
import keyword
import re
from collections.abc import Mapping
from pathlib import Path
from typing import Any

INDENT = " " * 4
IDENTIFIER_PATTERN = re.compile(r"\W+")


def _sanitize_identifier(name: str) -> str:
    sanitized = IDENTIFIER_PATTERN.sub("_", name).strip("_") or "value"
    if sanitized[0].isdigit():
        sanitized = f"n_{sanitized}"
    if keyword.iskeyword(sanitized):
        sanitized = f"{sanitized}_"
    return sanitized


def _class_name(path_segments: tuple[str, ...]) -> str:
    normalized_parts: list[str] = []
    for segment in path_segments:
        sanitized = _sanitize_identifier(segment)
        normalized_parts.extend(
            part[:1].upper() + part[1:]
            for part in sanitized.split("_")
            if part
        )
    normalized = "".join(normalized_parts)
    return f"_{normalized or 'Root'}"


def _entry_literal(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def _emit_namespace(
        payload: Mapping[str, Any],
        *,
        path_segments: tuple[str, ...],
        lines: list[str],
) -> str:
    class_name = _class_name(path_segments)
    child_lines: list[str] = []

    for key, value in payload.items():
        attribute_name = _sanitize_identifier(key)
        if isinstance(value, Mapping):
            child_class_name = _emit_namespace(
                value,
                path_segments=(*path_segments, key),
                lines=lines,
            )
            child_lines.append(
                f"{INDENT}{attribute_name}: {child_class_name} = {child_class_name}()"
            )
            continue

        if not isinstance(value, str):
            joined_path = ".".join((*path_segments, key))
            raise TypeError(
                f"La clave `{joined_path}` debe apuntar a una cadena o a un objeto."
            )

        translation_key = ".".join((*path_segments, key))
        child_lines.append(
            f"{INDENT}{attribute_name}: TranslationKey = TranslationKey("
            f'key="{translation_key}", default_text={_entry_literal(value)})'
        )

    lines.append(f"class {class_name}:")
    if child_lines:
        lines.extend(child_lines)
    else:
        lines.append(f"{INDENT}pass")
    lines.append("")
    return class_name


def _build_module(catalog_path: Path, payload: Mapping[str, Any]) -> str:
    lines = [
        "# Generated by aa_scripts/i18n/generate_i18n_keys.py. Do not edit manually.",
        "from __future__ import annotations",
        "",
        "from bigness_league_bot.core.localization import TranslationKey",
        "",
    ]

    top_level_entries: list[tuple[str, str]] = []
    for key, value in payload.items():
        if not isinstance(value, Mapping):
            raise TypeError(f"La clave raiz `{key}` debe contener un objeto.")
        class_name = _emit_namespace(value, path_segments=(key,), lines=lines)
        top_level_entries.append((_sanitize_identifier(key), class_name))

    lines.append("class I18nKeys:")
    for attribute_name, class_name in top_level_entries:
        lines.append(
            f"{INDENT}{attribute_name}: {class_name} = {class_name}()"
        )
    lines.append("")
    lines.append("I18N: I18nKeys = I18nKeys()")
    lines.append("")
    lines.append(f"# Source catalog: {catalog_path.as_posix()}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Genera un modulo Python con claves de i18n tipadas."
    )
    parser.add_argument(
        "--catalog",
        required=True,
        type=Path,
        help="Ruta al catalogo JSON base.",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Ruta del modulo Python generado.",
    )
    args = parser.parse_args()

    with args.catalog.open("r", encoding="utf-8-sig") as file:
        payload = json.load(file)

    if not isinstance(payload, Mapping):
        raise TypeError("El catalogo base debe contener un objeto JSON en la raiz.")

    rendered_module = _build_module(args.catalog, payload)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered_module, encoding="utf-8")


if __name__ == "__main__":
    main()
