# Generated by aa_scripts/i18n/generate_i18n_keys.py. Do not edit manually.
from __future__ import annotations

from bigness_league_bot.core.localization import TranslationKey


class _CommandsChannelManagementCloseChannelParametersAction:
    description: TranslationKey = TranslationKey(
        key="commands.channel_management.close_channel.parameters.action.description",
        default_text="Selecciona el tipo de cierre que quieres aplicar")

class _CommandsChannelManagementCloseChannelParameters:
    action: _CommandsChannelManagementCloseChannelParametersAction = _CommandsChannelManagementCloseChannelParametersAction()

class _CommandsChannelManagementCloseChannelChoices:
    match_played: TranslationKey = TranslationKey(key="commands.channel_management.close_channel.choices.match_played",
                                                  default_text="Partido jugado")
    matchday_closed: TranslationKey = TranslationKey(
        key="commands.channel_management.close_channel.choices.matchday_closed", default_text="Jornada cerrada")
    reopen_match: TranslationKey = TranslationKey(key="commands.channel_management.close_channel.choices.reopen_match",
                                                  default_text="Reabrir partido")
    delete_channel: TranslationKey = TranslationKey(
        key="commands.channel_management.close_channel.choices.delete_channel", default_text="Eliminacion de canal")

class _CommandsChannelManagementCloseChannel:
    name: TranslationKey = TranslationKey(key="commands.channel_management.close_channel.name",
                                          default_text="cerrar_canal")
    description: TranslationKey = TranslationKey(key="commands.channel_management.close_channel.description",
                                                 default_text="Aplica una accion de cierre sobre el canal actual.")
    parameters: _CommandsChannelManagementCloseChannelParameters = _CommandsChannelManagementCloseChannelParameters()
    choices: _CommandsChannelManagementCloseChannelChoices = _CommandsChannelManagementCloseChannelChoices()

class _CommandsChannelManagement:
    close_channel: _CommandsChannelManagementCloseChannel = _CommandsChannelManagementCloseChannel()

class _CommandsChannelAccessAddToChannel:
    name: TranslationKey = TranslationKey(key="commands.channel_access.add_to_channel.name",
                                          default_text="anadir_al_canal")
    description: TranslationKey = TranslationKey(key="commands.channel_access.add_to_channel.description",
                                                 default_text="Anade roles al canal actual con un selector filtrado.")

class _CommandsChannelAccess:
    add_to_channel: _CommandsChannelAccessAddToChannel = _CommandsChannelAccessAddToChannel()

class _CommandsMatchChannelCreationCreateMatchChannelParametersJornada:
    description: TranslationKey = TranslationKey(
        key="commands.match_channel_creation.create_match_channel.parameters.jornada.description",
        default_text="Numero de jornada del partido")

class _CommandsMatchChannelCreationCreateMatchChannelParametersPartido:
    description: TranslationKey = TranslationKey(
        key="commands.match_channel_creation.create_match_channel.parameters.partido.description",
        default_text="Numero de partido dentro de la jornada")

class _CommandsMatchChannelCreationCreateMatchChannelParametersCategoria:
    description: TranslationKey = TranslationKey(
        key="commands.match_channel_creation.create_match_channel.parameters.categoria.description",
        default_text="Division donde se creara el canal")

class _CommandsMatchChannelCreationCreateMatchChannelParametersEquipo1:
    description: TranslationKey = TranslationKey(
        key="commands.match_channel_creation.create_match_channel.parameters.equipo_1.description",
        default_text="Rol del primer equipo")

class _CommandsMatchChannelCreationCreateMatchChannelParametersEquipo2:
    description: TranslationKey = TranslationKey(
        key="commands.match_channel_creation.create_match_channel.parameters.equipo_2.description",
        default_text="Rol del segundo equipo")

class _CommandsMatchChannelCreationCreateMatchChannelParameters:
    jornada: _CommandsMatchChannelCreationCreateMatchChannelParametersJornada = _CommandsMatchChannelCreationCreateMatchChannelParametersJornada()
    partido: _CommandsMatchChannelCreationCreateMatchChannelParametersPartido = _CommandsMatchChannelCreationCreateMatchChannelParametersPartido()
    categoria: _CommandsMatchChannelCreationCreateMatchChannelParametersCategoria = _CommandsMatchChannelCreationCreateMatchChannelParametersCategoria()
    equipo_1: _CommandsMatchChannelCreationCreateMatchChannelParametersEquipo1 = _CommandsMatchChannelCreationCreateMatchChannelParametersEquipo1()
    equipo_2: _CommandsMatchChannelCreationCreateMatchChannelParametersEquipo2 = _CommandsMatchChannelCreationCreateMatchChannelParametersEquipo2()

class _CommandsMatchChannelCreationCreateMatchChannelChoices:
    gold_division: TranslationKey = TranslationKey(
        key="commands.match_channel_creation.create_match_channel.choices.gold_division", default_text="Gold Division")
    silver_division: TranslationKey = TranslationKey(
        key="commands.match_channel_creation.create_match_channel.choices.silver_division",
        default_text="Silver Division")

class _CommandsMatchChannelCreationCreateMatchChannel:
    name: TranslationKey = TranslationKey(key="commands.match_channel_creation.create_match_channel.name",
                                          default_text="canal_de_jornada")
    description: TranslationKey = TranslationKey(key="commands.match_channel_creation.create_match_channel.description",
                                                 default_text="Crea un canal de partido para una jornada concreta.")
    parameters: _CommandsMatchChannelCreationCreateMatchChannelParameters = _CommandsMatchChannelCreationCreateMatchChannelParameters()
    choices: _CommandsMatchChannelCreationCreateMatchChannelChoices = _CommandsMatchChannelCreationCreateMatchChannelChoices()

class _CommandsMatchChannelCreation:
    create_match_channel: _CommandsMatchChannelCreationCreateMatchChannel = _CommandsMatchChannelCreationCreateMatchChannel()

class _Commands:
    channel_management: _CommandsChannelManagement = _CommandsChannelManagement()
    channel_access: _CommandsChannelAccess = _CommandsChannelAccess()
    match_channel_creation: _CommandsMatchChannelCreation = _CommandsMatchChannelCreation()

class _MessagesAdminSync:
    invalid_scope: TranslationKey = TranslationKey(key="messages.admin.sync.invalid_scope",
                                                   default_text="Usa `!sync guild` o `!sync global`.")
    invalid_usage: TranslationKey = TranslationKey(key="messages.admin.sync.invalid_usage",
                                                   default_text="Usa `!sync guild`, `!sync global`, `!sync prune guild`, `!sync prune global` o `!sync prune other`.")
    guild_id_required: TranslationKey = TranslationKey(key="messages.admin.sync.guild_id_required",
                                                       default_text="No se puede operar sobre comandos de guild sin `DISCORD_GUILD_ID`.")
    scope_locked: TranslationKey = TranslationKey(key="messages.admin.sync.scope_locked",
                                                  default_text="El bot esta configurado para `BOT_SYNC_SCOPE={sync_scope}`. Cambia el `.env` y reinicia si quieres usar el otro scope.")
    completed: TranslationKey = TranslationKey(key="messages.admin.sync.completed",
                                               default_text="Sincronizacion completada: {summary}")
    pruned: TranslationKey = TranslationKey(key="messages.admin.sync.pruned",
                                            default_text="Limpieza completada: {summary}")

class _MessagesAdminSlashStatus:
    result: TranslationKey = TranslationKey(key="messages.admin.slash_status.result",
                                            default_text="Estado local de slash commands: guild_id={guild_id} commands=[{commands}]")

class _MessagesAdmin:
    sync: _MessagesAdminSync = _MessagesAdminSync()
    slash_status: _MessagesAdminSlashStatus = _MessagesAdminSlashStatus()

class _MessagesChannelManagement:
    delete_prompt: TranslationKey = TranslationKey(key="messages.channel_management.delete_prompt",
                                                   default_text="Vas a eliminar el canal `{channel_name}` de forma permanente.\nRoles protegidos del sistema: {protected_roles}.\nConfirma solo si estas completamente seguro.")

class _MessagesChannelRoleAdditionButtons:
    previous: TranslationKey = TranslationKey(key="messages.channel_role_addition.buttons.previous",
                                              default_text="Anterior")
    next: TranslationKey = TranslationKey(key="messages.channel_role_addition.buttons.next", default_text="Siguiente")
    confirm: TranslationKey = TranslationKey(key="messages.channel_role_addition.buttons.confirm",
                                             default_text="Confirmar")
    cancel: TranslationKey = TranslationKey(key="messages.channel_role_addition.buttons.cancel",
                                            default_text="Cancelar")
    search: TranslationKey = TranslationKey(key="messages.channel_role_addition.buttons.search", default_text="Buscar")
    clear_filter: TranslationKey = TranslationKey(key="messages.channel_role_addition.buttons.clear_filter",
                                                  default_text="Limpiar filtro")

class _MessagesChannelRoleAdditionModal:
    title: TranslationKey = TranslationKey(key="messages.channel_role_addition.modal.title",
                                           default_text="Buscar roles")
    query_label: TranslationKey = TranslationKey(key="messages.channel_role_addition.modal.query_label",
                                                 default_text="Nombre, ID o mencion del rol")
    query_placeholder: TranslationKey = TranslationKey(key="messages.channel_role_addition.modal.query_placeholder",
                                                       default_text="Ejemplo: Dragons, 123456789 o <@&123456789>")

class _MessagesChannelRoleAddition:
    loading_placeholder: TranslationKey = TranslationKey(key="messages.channel_role_addition.loading_placeholder",
                                                         default_text="Cargando roles...")
    empty_option_label: TranslationKey = TranslationKey(key="messages.channel_role_addition.empty_option_label",
                                                        default_text="Sin roles")
    no_results_label: TranslationKey = TranslationKey(key="messages.channel_role_addition.no_results_label",
                                                      default_text="Sin resultados")
    no_results_placeholder: TranslationKey = TranslationKey(key="messages.channel_role_addition.no_results_placeholder",
                                                            default_text="No hay roles para mostrar")
    select_placeholder: TranslationKey = TranslationKey(key="messages.channel_role_addition.select_placeholder",
                                                        default_text="Selecciona roles de la pagina {page}/{page_count}")
    buttons: _MessagesChannelRoleAdditionButtons = _MessagesChannelRoleAdditionButtons()
    modal: _MessagesChannelRoleAdditionModal = _MessagesChannelRoleAdditionModal()
    render_content: TranslationKey = TranslationKey(key="messages.channel_role_addition.render_content",
                                                    default_text="Selecciona los roles que quieres anadir a este canal.\nRango filtrado: `{range_start}` < roles < `{range_end}`.\nPagina {page}/{page_count} | Seleccionados: {selected_count} | Disponibles: {visible_count}/{candidate_count}.\nBusqueda: {search_query}.\nUsa Confirmar para aplicar los permisos al canal.")
    search_none: TranslationKey = TranslationKey(key="messages.channel_role_addition.search_none",
                                                 default_text="sin filtro")
    only_actor: TranslationKey = TranslationKey(key="messages.channel_role_addition.only_actor",
                                                default_text="Solo quien ejecuto el comando puede usar este selector.")
    timeout: TranslationKey = TranslationKey(key="messages.channel_role_addition.timeout",
                                             default_text="La seleccion de roles ha expirado. No se han aplicado cambios.")
    select_before_confirm: TranslationKey = TranslationKey(key="messages.channel_role_addition.select_before_confirm",
                                                           default_text="Selecciona al menos un rol antes de confirmar.")
    selection_cancelled: TranslationKey = TranslationKey(key="messages.channel_role_addition.selection_cancelled",
                                                         default_text="Seleccion de roles cancelada.")

class _MessagesChannelDeleteConfirmationButtons:
    confirm: TranslationKey = TranslationKey(key="messages.channel_delete_confirmation.buttons.confirm",
                                             default_text="Confirmar eliminacion")
    cancel: TranslationKey = TranslationKey(key="messages.channel_delete_confirmation.buttons.cancel",
                                            default_text="Cancelar")

class _MessagesChannelDeleteConfirmation:
    only_actor: TranslationKey = TranslationKey(key="messages.channel_delete_confirmation.only_actor",
                                                default_text="Solo quien ejecuto el comando puede confirmar esta accion.")
    timeout: TranslationKey = TranslationKey(key="messages.channel_delete_confirmation.timeout",
                                             default_text="La confirmacion ha expirado. No se ha eliminado el canal.")
    deleting: TranslationKey = TranslationKey(key="messages.channel_delete_confirmation.deleting",
                                              default_text="Eliminando canal...")
    cancelled: TranslationKey = TranslationKey(key="messages.channel_delete_confirmation.cancelled",
                                               default_text="Eliminacion cancelada.")
    buttons: _MessagesChannelDeleteConfirmationButtons = _MessagesChannelDeleteConfirmationButtons()


class _MessagesMatchChannelCreationWelcomeEmbedsDetails:
    title: TranslationKey = TranslationKey(key="messages.match_channel_creation.welcome.embeds.details.title",
                                           default_text="\ud83d\udd30 Detalles a tener en cuenta \ud83d\udd30")
    description: TranslationKey = TranslationKey(
        key="messages.match_channel_creation.welcome.embeds.details.description",
        default_text="- Si nadie se pone **de acuerdo** y no hay una fecha por ninguno de los **dos equipos**, el partido se dara como **nulo**. Ninguno de los dos equipos presentes sumara puntos esta jornada.\n- Pongamos todos de nuestra parte para poder **jugar el partido** y recordad **organizarlo** lo **antes posible**.\n- Intentad ser **flexibles ambos equipos**. Si alguno no puede, debe **proponer** otra **fecha** y asi sucesivamente.\n- Habra **minutos** de **cortesia** segun la **hora del partido**. Si la fecha esta puesta a las **16:00**, como tarde debera iniciarse a las **16:10**, salvo acuerdo expreso entre ambos equipos.")


class _MessagesMatchChannelCreationWelcomeEmbedsIssues:
    title: TranslationKey = TranslationKey(key="messages.match_channel_creation.welcome.embeds.issues.title",
                                           default_text="\ud83d\udd30 En caso de problemas \ud83d\udd30")
    description: TranslationKey = TranslationKey(
        key="messages.match_channel_creation.welcome.embeds.issues.description",
        default_text="- Si se **cancela** el partido **1h antes** porque el equipo **rival** al final **no puede**, muy probablemente sea **free win**, salvo que el equipo rival acepte jugarlo en otra fecha. Esta situacion la evaluara un **Staff**.\n- Cualquier **problema** relacionado con el **partido** debe documentarse con pruebas:\n - Sacad **capturas** de incidentes.\n - Guardad evidencias de comportamientos **toxicos**.\n - Registrad cualquier **incidencia del partido**.\n- El partido se dara como **finalizado** cuando alguien del Staff ponga el canal en **modo lectura**. Para cualquier **apelacion** se debera **abrir un ticket**.")


class _MessagesMatchChannelCreationWelcomeEmbedsMatchData:
    title: TranslationKey = TranslationKey(key="messages.match_channel_creation.welcome.embeds.match_data.title",
                                           default_text="\u26bd \ud83d\ude97 Datos del partido \ud83d\ude97 \u26bd")
    description: TranslationKey = TranslationKey(
        key="messages.match_channel_creation.welcome.embeds.match_data.description",
        default_text="- Informacion del partido\n - Jornada: {jornada_emoji}\n - Partido: {partido_emoji}\n - Equipos: {team_one} vs {team_two}\n - Formato: Bo5 (al mejor de 5 partidos)\n - Fecha y hora: Pendiente de definir entre ambos equipos\n- Sala privada\n - Nombre: `staff`\n - Contrasena: `staff`")


class _MessagesMatchChannelCreationWelcomeEmbeds:
    details: _MessagesMatchChannelCreationWelcomeEmbedsDetails = _MessagesMatchChannelCreationWelcomeEmbedsDetails()
    issues: _MessagesMatchChannelCreationWelcomeEmbedsIssues = _MessagesMatchChannelCreationWelcomeEmbedsIssues()
    match_data: _MessagesMatchChannelCreationWelcomeEmbedsMatchData = _MessagesMatchChannelCreationWelcomeEmbedsMatchData()


class _MessagesMatchChannelCreationWelcomeButtons:
    create_ticket: TranslationKey = TranslationKey(key="messages.match_channel_creation.welcome.buttons.create_ticket",
                                                   default_text="Crear ticket")
    rules: TranslationKey = TranslationKey(key="messages.match_channel_creation.welcome.buttons.rules",
                                           default_text="Normativa - Bigness League")


class _MessagesMatchChannelCreationWelcome:
    content: TranslationKey = TranslationKey(key="messages.match_channel_creation.welcome.content",
                                             default_text="# Jornada {jornada_emoji}  Partido {partido_emoji}\n_ _\n## Bienvenid@s a {team_one} y {team_two}\n\nEste es el canal privado autogenerado de vuestro partido. Recordad que para acordar fechas, pruebas y todo lo relacionado con esta jornada debereis hablar unicamente por este canal de texto. Si se acuerda el partido por medios externos y surge algun problema a futuro, no se tendra en cuenta. Los casos mas graves los evaluara el Staff.\n\nMucha suerte a ambos equipos.\n\n_ _")
    embeds: _MessagesMatchChannelCreationWelcomeEmbeds = _MessagesMatchChannelCreationWelcomeEmbeds()
    buttons: _MessagesMatchChannelCreationWelcomeButtons = _MessagesMatchChannelCreationWelcomeButtons()


class _MessagesMatchChannelCreation:
    welcome: _MessagesMatchChannelCreationWelcome = _MessagesMatchChannelCreationWelcome()

class _Messages:
    admin: _MessagesAdmin = _MessagesAdmin()
    channel_management: _MessagesChannelManagement = _MessagesChannelManagement()
    channel_role_addition: _MessagesChannelRoleAddition = _MessagesChannelRoleAddition()
    channel_delete_confirmation: _MessagesChannelDeleteConfirmation = _MessagesChannelDeleteConfirmation()
    match_channel_creation: _MessagesMatchChannelCreation = _MessagesMatchChannelCreation()

class _ErrorsChannelManagement:
    server_only: TranslationKey = TranslationKey(key="errors.channel_management.server_only",
                                                 default_text="Este comando solo se puede usar dentro de un servidor.")
    text_only: TranslationKey = TranslationKey(key="errors.channel_management.text_only",
                                               default_text="Este comando solo se puede usar dentro de un canal de texto.")
    invalid_channel_name: TranslationKey = TranslationKey(key="errors.channel_management.invalid_channel_name",
                                                          default_text="Este comando solo se puede usar en canales con nombre tipo `\u300e\ud835\udddd\u300f1\ufe0f\u20e3\u300e\ud835\udde3\u300f4\ufe0f\u20e3\u30fb\u26bd`, `\u300e\ud835\udddd\u300f1\ufe0f\u20e3\u300e\ud835\udde3\u300f4\ufe0f\u20e3\u30fb\u2705` o `\u300e\ud835\udddd\u300f1\ufe0f\u20e3\u300e\ud835\udde3\u300f4\ufe0f\u20e3\u30fb\ud83d\udd12`.")
    unauthorized_role: TranslationKey = TranslationKey(key="errors.channel_management.unauthorized_role",
                                                       default_text="Solo pueden usar este comando los roles: {protected_roles}.")
    protected_roles_missing: TranslationKey = TranslationKey(key="errors.channel_management.protected_roles_missing",
                                                             default_text="Faltan roles protegidos en el servidor: {missing_roles}.")
    invalid_role_not_in_guild: TranslationKey = TranslationKey(
        key="errors.channel_management.invalid_role_not_in_guild",
        default_text="El rol `{role_name}` no pertenece a este servidor.")
    invalid_role_everyone: TranslationKey = TranslationKey(key="errors.channel_management.invalid_role_everyone",
                                                           default_text="No puedes anadir `@everyone` al canal.")
    no_valid_additional_roles: TranslationKey = TranslationKey(
        key="errors.channel_management.no_valid_additional_roles",
        default_text="Selecciona al menos un rol adicional valido.")
    range_start_missing: TranslationKey = TranslationKey(key="errors.channel_management.range_start_missing",
                                                         default_text="No existe el rol de inicio configurado para el selector: `{role_id}`.")
    range_end_missing: TranslationKey = TranslationKey(key="errors.channel_management.range_end_missing",
                                                       default_text="No existe el rol de fin configurado para el selector: `{role_id}`.")
    range_empty: TranslationKey = TranslationKey(key="errors.channel_management.range_empty",
                                                 default_text="No hay roles seleccionables entre los separadores configurados.")

class _ErrorsMatchChannelCreation:
    same_team_roles: TranslationKey = TranslationKey(key="errors.match_channel_creation.same_team_roles",
                                                     default_text="No puedes crear un partido usando el mismo rol dos veces: `{role_name}`.")
    invalid_team_role: TranslationKey = TranslationKey(key="errors.match_channel_creation.invalid_team_role",
                                                       default_text="El rol `{role_name}` no se puede usar como equipo en un canal de partido.")
    team_role_out_of_range: TranslationKey = TranslationKey(key="errors.match_channel_creation.team_role_out_of_range",
                                                            default_text="El rol `{role_name}` no esta dentro del rango de roles de equipos configurado: `{range_start}` < rol < `{range_end}`.")
    channel_already_exists: TranslationKey = TranslationKey(key="errors.match_channel_creation.channel_already_exists",
                                                            default_text="Ya existe un canal para esa jornada y ese partido: `{channel_name}`.")
    category_missing: TranslationKey = TranslationKey(key="errors.match_channel_creation.category_missing",
                                                      default_text="No existe la categoria configurada para crear este canal: `{category_id}`.")

class _ErrorsSlash:
    forbidden: TranslationKey = TranslationKey(key="errors.slash.forbidden",
                                               default_text="No tienes permisos para ejecutar este comando.")
    bot_missing_permissions: TranslationKey = TranslationKey(key="errors.slash.bot_missing_permissions",
                                                             default_text="El bot necesita permisos suficientes para gestionar el canal.")
    discord_forbidden: TranslationKey = TranslationKey(key="errors.slash.discord_forbidden",
                                                       default_text="Discord ha rechazado la accion. Revisa los permisos del bot.")
    http_error: TranslationKey = TranslationKey(key="errors.slash.http_error",
                                                default_text="Discord ha devuelto un error al actualizar el canal.")
    unexpected: TranslationKey = TranslationKey(key="errors.slash.unexpected",
                                                default_text="Ha ocurrido un error inesperado al procesar el comando.")

class _Errors:
    channel_management: _ErrorsChannelManagement = _ErrorsChannelManagement()
    match_channel_creation: _ErrorsMatchChannelCreation = _ErrorsMatchChannelCreation()
    slash: _ErrorsSlash = _ErrorsSlash()

class _ActionsChannelManagement:
    match_played_summary: TranslationKey = TranslationKey(key="actions.channel_management.match_played_summary",
                                                          default_text="Canal puesto en modo solo lectura para el resto de roles. Staff, Administrador y Ceo mantienen escritura.")
    matchday_closed_summary: TranslationKey = TranslationKey(key="actions.channel_management.matchday_closed_summary",
                                                             default_text="Canal cerrado para roles no protegidos. Solo Staff, Administrador y Ceo conservan acceso.")
    reopen_summary: TranslationKey = TranslationKey(key="actions.channel_management.reopen_summary",
                                                    default_text="Canal reabierto. Se ha restaurado la escritura para los roles con acceso al canal.")
    reopen_with_roles_summary: TranslationKey = TranslationKey(
        key="actions.channel_management.reopen_with_roles_summary",
        default_text="Canal reabierto. Se ha restaurado la escritura para los roles con acceso al canal y se han anadido estos roles: {roles}.")
    add_roles_summary: TranslationKey = TranslationKey(key="actions.channel_management.add_roles_summary",
                                                       default_text="Se han anadido al canal estos roles: {roles}.")

class _ActionsMatchChannelCreation:
    created_summary: TranslationKey = TranslationKey(key="actions.match_channel_creation.created_summary",
                                                     default_text="Se ha creado {channel} en `{category}` para la jornada {jornada}, partido {partido}, entre {team_one} y {team_two}, y se ha enviado el mensaje inicial del canal.")

class _Actions:
    channel_management: _ActionsChannelManagement = _ActionsChannelManagement()
    match_channel_creation: _ActionsMatchChannelCreation = _ActionsMatchChannelCreation()

class I18nKeys:
    commands: _Commands = _Commands()
    messages: _Messages = _Messages()
    errors: _Errors = _Errors()
    actions: _Actions = _Actions()

I18N: I18nKeys = I18nKeys()

# Source catalog: aa_resources/locales/es-ES.json
